version: "2.2"

services:
  redis:
    image: redis
    mem_limit: 100M
    restart: always
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports: # this can be removed after initial migrations
      - "5432:5432"
  app:
    build: ./ # or image: jimmyl02/guessrapp:latest
    cpus: 0.75
    mem_limit: 400M
    environment:
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_URL=${REDIS_URL}
        - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
        - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
        - ORIGIN=${ORIGIN}
    depends_on:
      - redis
      - postgres
    restart: always
    ports:
        - "80:8080"

volumes: 
  pgdata: