apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: guessrapp-app
  ports:
  - protocol: TCP
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: guessrapp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guessrapp-app
  template:
    metadata:
      labels:
        app: guessrapp-app
    spec:
      restartPolicy: Always
      containers:
      - name: app
        image: us-west2-docker.pkg.dev/guessrapp/app/app:0.1
        ports:
          - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: REDIS_URL
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: SPOTIFY_CLIENT_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: SPOTIFY_CLIENT_SECRET
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 3